theme: jekyll-theme-minimal
title: Aprendizado Profundo - DCC/UFMG
description: Material do curso extensão de aprendizado profundo (deep learning) sendo ofertado no DCC/UFMG.
logo: logo.png
show_downloads: false
